version: '3.8'
services:
  db:
    container_name: netopg13
    image: postgres:13
    environment:
      POSTGRES_USER: alsok
      POSTGRES_PASSWORD: netopg13
      POSTGRES_DB: neto6db4
    ports:
      - "5432:5432"
    volumes:      
      - db_vol:/var/lib/postgresql/data/
      - ./test_dump.sql:/var/lib/postgresql/test_dump.sql:ro
volumes:
  db_vol:
  


    

